# autogenerated by txs
#include:beamerbasearticle
#include:beamerbasemodes
\unprocessedoptions-beamerbasearticle.sty#S
\unprocessedoptions-beamerbasemodes.sty#S
beamerbasearticle.sty#S
beamerbasemodes.sty#S
csnameendcsname#S
