# autogenerated by txs
#include:atbegshi
#include:iftex
#include:lscape
\pdfpageattr#S
\__hook iftex#S
\__hook lscape#S
\unprocessedoptions-iftex.sty#S
\unprocessedoptions-lscape.sty#S
csnameendcsname#S
iftex.sty#S
lscape.sty#S
